### ISSUE TITLE
Left speaker outside station not playing

### ISSUE THREAD

**Issue by yj9** [CiTR/Other#5]

**Comment by citrtech** [comment]
-Jonathan Notes:
          -Speaker is fine upon power cycle
          -Turns off after a small amount of time
          -Speaker seems to run inconsistently (sometime runs for a short time, sometime runs fine for days)

Best Guess, mono track plays, speaker doesn't see audio for a while, goes into standby mode and won't leave this mode until power is cycled again.

**Comment by citrtech** [comment]
Jonathan and I looked over the black speaker outside that is causing issues. There was a mono track playing at the time (yesterday around 5pm), and we checked this by switching the inputs of the speakers. When done the white speaker wouldn't play and the black speaker did. 

Jonathan also mentioned that he had seen the problem speaker turn off after running for a while. To make sure it isn't having power issues we are leaving the problem speaker connected with both L & R combined as one input and leaving it for a week. Wait till later next week and check on daily to make sure it is still running. 

ALSO, need to check if the antenna is broadcasting Mono.

**Comment by citrtech** [comment]
Started creating Lucid Diagram of Studio B.

**Comment by citrtech** [comment]
Confirmed with Saman last week that the antenna is working fine and broadcasting stereo.

**Comment by citrtech** [comment]
Yesterday, I tested the multiple inputs/outputs for Headphone Amplifier. After checking my results with Saman, we concluded that (for whatever reason), the levels of static heard through the headphones was from having the signal come in through the XLR inputs or the TRS 1/4" inputs. 

For whatever reason, the RCA inputs exhibited normal/acceptable levels of static when tested. So as a work around we decided to use the Peavey Interface Amplifier. 

So, with the new current setup, the signal comes through ethernet, gets converted to dual XLR (L&R) from the splitter, and then is converted to dual RCA via the interface amplifier. After which it is fed to the RCA inputs of the headphone amplifier.

Because the interface amplifier is also being used for the aux device input, we tested the setup with both channels running where the computer is playing music to the headphones and my phone was sending music to the board through the aux cable. This didn't affect the quality of either signal so the setup will remain.

In effect, I need to alter the hardware Draw.IO diagram. Also I will need to implement the same solution in studio C.

**Comment by citrtech** [comment]
After leaving the black speaker with both L&R inputs feeding it for a couple weeks it was observed that the speaker never shut off.

To see if there are problems related to the speaker entering rest mode I plan to take down the black speaker, leave it with power running for an hour or so and then will try feeding it audio input to see if it won't play it.

**Comment by citrtech** [comment]
While waiting to take down the speaker tomorrow I did more testing to figure out other possible issues. 

First, I tested the Ethernet to RCA adapter in studio B by connecting it between the Axia Core and the Headphone Amplifier. No problems there.

Second I tested the signal coming through the Ethernet cable directly by plugging the Ethernet from the wall jack into the headphone amplifier (which I borrowed from studio B) and listened to the signal using a pair of working headphones. 

From this I discovered that the green RCA delivers a good signal, while the red RCA delivers an extremely weak signal that could only be hear by maxing the amplification on the amplifier. 

To make sure that it wasn't the Ethernet cable causing issues I temporarily swapped the short Ethernet cord currently being used for the long one used in studio B for the headphone amplifier which I knew worked. This did nothing to resolve the weak red RCA issue.

SO, after all the testing, it turns out that the issue is with the port or somewhere between the port and the server. For reference, the port being used is WLL502-2/ LL515-P1-12

**Comment by citrtech** [comment]
Saman and I tested a few more areas of the system today.

Using the mini mixing board and a pair of headphones in the server room, we tested the Ethernet line coming from the antenna. No weakness in the signal was on either side was detected, even when we min/maxed the pan for each side.

To see if it was the port, we tested the port outside with the same setup, and again, no weakness was detected.

So, the issue is intermittent, unfortunately...

In the meantime, I need to do two things:

1) At the start of my next shift, set up a speaker of the same model in the server room without music, leave it on for a few hours and then see if music will play through without issue. 

2) Wait for the next time the issue occurs outside, and then try testing the signal with the mini mixing board.

**Comment by citrtech** [comment]
More testing has been done, and the results are weird.

Upon arrival today I noticed that one of the sides outside wasn't playing. 
Using the radio I setup in the server room, I confirmed that the signal being put out on the air was fine, since the radio itself could still pan to either side without any issue.

To see if maybe the issue is with the feed coming in through the "Outside Signal" Ethernet cable, I plugged it into the mini mixing board and listened to the signal over headphones to find no issues with the signal at all. 

When I plug the Ethernet cable back into the switch port, the problem outside seems to fix itself as well...

**Comment by citrtech** [comment]
GOOD NEWS!

The problem has occurred for the outside speakers again, but this time the problem didn't disappear quickly. AND I was able to hear the problem through the mixing board in the server room when I plugged in the Ethernet cable that usually is connected to the "Outside Signal" port in the Amp Netconnect module. 

So somewhere down this line the error is occurring. While this might make things more challenging, I am just happy to be able to eliminate everything after that point as a possible cause of error.
